project:
  type: book

book:
  title: "Smux Cahier de Note"
  author: "Nathanaël MUOT"
  date: "04/25/2023"
  chapters:
    - index.qmd
    - prologue.qmd
    - intro.qmd
#    - summary.qmd
    - part: num/index.qmd
      chapters:
        - num/01_un_mode_finie.qmd
        - num/02_DFT.qmd
        #- num/03_DFT_pratique.qmd
    - part: interviews/index.qmd
      chapters:
        - interviews/algo_and_numerical.qmd
    - references.qmd

bibliography: biblio/references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  # pdf:
  #   documentclass: scrreprt



