project:
  type: book

book:
  title: "Smux Cahier de Note"
  author: "Nathanaël MUOT"
  date: "16/01/2023"
  chapters:
    - index.qmd
    - prologue.qmd
    - intro.qmd
#    - summary.qmd
    - 01_un_mode_finie.qmd
    - 02_DFT.qmd
    - 03_DFT_pratique.qmd
    - references.qmd

bibliography: biblio/references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt



